name: Benchmark

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/**'
      - 'benchmarks/**'
      - '.github/workflows/benchmark.yml'
      - '.mise.toml'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
      - name: Install dependencies
        run: |
          mise exec -- npm install
          mise exec -- npm run build
      - name: Run benchmark
        run: |
          cd benchmarks
          mise exec -- npm install
          mise exec -- npm exec --package tsx -- tsx func.mjs | tee output.txt
      - name: Download previous benchmark data
        uses: actions/cache@v5
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tool: 'benchmarkjs'
          output-file-path: ./benchmarks/output.txt
          external-data-json-path: ./cache/benchmark-data.json
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@zfben'
